export const ANSWER_MAX_LENGTH = 21;
export const ANSWER_WILDCARD_LETTER = '*';
export const DEFAULT_ANSWER = 'Reisen Udongein Inaba';

export const NameList = [
    'Hakurei Reimu',
    'Kirisame Marisa',
    'SinGyoku',
    'YuugenMagan',
    'Elis',
    'Sariel',
    'Mima',
    'Kikuri',
    'Konngara',
    'Genjii',
    'Rika',
    'Meira',
    'Ellen',
    'Kotohime',
    'Kana Anaberal',
    'Asakura Rikako',
    'Kitashirakawa Chiyuri',
    'Okazaki Yumemi',
    'Ruukoto',
    'Orange',
    'Kurumi',
    'Elly',
    'Kazami Yuuka',
    'Mugetsu',
    'Gengetsu',
    'Sara',
    'Louise',
    'Alice Margatroid',
    'Yuki',
    'Mai',
    'Ayana',
    'Yumeko',
    'Shinki',
    'Rumia',
    'Daiyousei',
    'Cirno',
    'Hong Meiling',
    'Koakuma',
    'Patchouli Knowledge',
    'Izayoi Sakuya',
    'Remilia Scarlet',
    'Flandre Scarlet',
    'Satsuki Rin',
    'Letty Whiterock',
    'Chen',
    'Lily White',
    'Lyrica Prismriver',
    'Lunasa Prismriver',
    'Merlin Prismriver',
    'Konpaku Youmu',
    'Saigyouji Yuyuko',
    'Yakumo Ran',
    'Yakumo Yukari',
    'Layla Prismriver',
    'Konpaku Youki',
    'Saigyou Ayakashi',
    'Ibuki Suika',
    'Wriggle Nightbug',
    'Mystia Lorelei',
    'Kamishirasawa Keine',
    'Inaba Tewi',
    'Reisen Udongein Inaba',
    'Yagokoro Eirin',
    'Houraisan Kaguya',
    'Fujiwara no Mokou',
    'Shameimaru Aya',
    'Medicine Melancholy',
    'Onozuka Komachi',
    'Shiki Eiki',
    'Aki Shizuha',
    'Aki Minoriko',
    'Kagiyama Hina',
    'Kawashiro Nitori',
    'Inubashiri Momiji',
    'Kochiya Sanae',
    'Yasaka Kanako',
    'Moriya Suwako',
    'Mishaguji',
    'Nagae Iku',
    'Hinanawi Tenshi',
    'Kisume',
    'Kurodani Yamame',
    'Mizuhashi Parsee',
    'Hoshiguma Yuugi',
    'Komeiji Satori',
    'Kaenbyou Rin',
    'Reiuji Utsuho',
    'Komeiji Koishi',
    'Nazrin',
    'Tatara Kogasa',
    'Kumoi Ichirin',
    'Unzan',
    'Murasa Minamitsu',
    'Toramaru Shou',
    'Hijiri Byakuren',
    'Houjuu Nue',
    'Hijiri Myouren',
    'Hisoutensoku',
    'Himekaidou Hatate',
    'Kasodani Kyouko',
    'Miyako Yoshika',
    'Kaku Seiga',
    'Soga no Tojiko',
    'Mononobe no Futo',
    'Toyosatomimi no Miko',
    'Futatsuiwa Mamizou',
    'Hata no Kokoro',
    'Wakasagihime',
    'Sekibanki',
    'Imaizumi Kagerou',
    'Tsukumo Benben',
    'Tsukumo Yatsuhashi',
    'Kijin Seija',
    'Sukuna Shinmyoumaru',
    'Horikawa Raiko',
    'Usami Sumireko',
    'Seiran',
    'Ringo',
    'Doremy Sweet',
    'Kishin Sagume',
    'Clownpiece',
    'Junko',
    'Hecatia Lapislazuli',
    'Yorigami Joon',
    'Yorigami Shion',
    'Eternity Larva',
    'Sakata Nemuno',
    'Komano Aunn',
    'Yatadera Narumi',
    'Nishida Satono',
    'Teireida Mai',
    'Matara Okina',
    'Ebisu Eika',
    'Ushizaki Urumi',
    'Niwatari Kutaka',
    'Kicchou Yachie',
    'Joutouguu Mayumi',
    'Haniyasushin Keiki',
    'Kurokoma Saki',
    'Toutetsu Yuuma',
    'Goutokuji Mike',
    'Yamashiro Takane',
    'Komakusa Sannyo',
    'Tamatsukuri Misumaru',
    'Kudamaki Tsukasa',
    'Iizunamaru Megumu',
    'Tenkyuu Chimata',
    'Himemushi Momoyo',
    'Biten Son',
    'Mitsugashira Enoko',
    'Tenkajin Chiyari',
    'Yomotsu Hisami',
    'Nippaku Zanmu',
    'Chirizuka Ubame',
    'Houjuu Chimi',
    'Michigami Nareko',
    'Yuiman Asama',
    'Iwanaga Ariya',
    'Watari Nina',
    'Morichika Rinnosuke',
    'Tokiko',
    'Luna Child',
    'Star Sapphire',
    'Sunny Milk',
    'Watatsuki no Toyohime',
    'Watatsuki no Yorihime',
    'Iwakasa',
    'Ibaraki Kasen',
    'Motoori Kosuzu',
    'Miyadeguchi Mizuchi',
    'Okunoda Miyoi',
].map(entry => entry.toUpperCase());

export const LetterList = [
    ' ',
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
].map(entry => entry.toUpperCase());
export const LetterMap = LetterList.reduce<Record<string, { letter: string, position: number }>>(
    (acc, letter, index) => {
        acc[letter] = { letter, position: index };
        return acc;
    },
    {},
);
export const JoinedLetterList = LetterList.join('');

export type LetterData = {
    key: string;
    letter: string;
    index: number;
    status: number;
};
export type GuessStatus = 'initial' | 'playing' | 'finished' | 'wrong-answer';
export const GuessStatusMap: Record<GuessStatus, { label: string }> = {
    "wrong-answer": {
        label: 'Wrong Answer',
    },
    finished: {
        label: 'Correct',
    },
    initial: {
        label: 'Started',
    },
    playing: {
        label: 'Is Playing',
    },
};

export type AnswerObject = {
    value: string,
    letterList: LetterData[],
};